policies:
- type: commit
  spec:
    headerLength: 89
    dco: true
    gpg: true
- type: conventionalCommit
  spec:
    types:
    - chore
    - docs
    - perf
    - refactor
    - style
    - test
    scopes:
    - policy
    - '*'
