metadata:
  repository: autonomy/conform

policies:
  - type: conventionalCommit
    spec:
      types:
        - "chore"
        - "docs"
        - "perf"
        - "refactor"
        - "style"
        - "test"
      scopes:
        - "ci"
        - "docker"
        - "git"
        - "metadata"
        - "policy"
        - "readme"
        - "renderer"
        - "*"

script:
  template: |
    {{ fromURL "https://raw.githubusercontent.com/autonomy/conform-templates/master/docker/deploy.sh" }}

pipeline:
  stages:
    - test
    - build

stages:
  test:
    artifacts:
      - source: /go/src/github.com/autonomy/conform/coverage.txt
        destination: coverage.txt
    tasks:
      - test
  build:
    tasks:
      - binary
      - image

tasks:
  binary:
    template: |
      FROM autonomy/golang:1.8.3 as binary
      WORKDIR $GOPATH/src/github.com/{{ .Repository }}
      COPY ./ ./
      {{ if and .Git.IsClean .Git.IsTag }}
      RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /conform -ldflags "-X \"github.com/{{ .Repository }}/pkg/version.Tag={{ trimAll "v" .Git.Tag }}\" -X \"github.com/{{ .Repository }}/pkg/version.SHA={{ .Git.SHA }}\" -X \"github.com/{{ .Repository }}/pkg/version.Built={{ .Built }}\""
      {{ else if .Git.IsClean }}
      RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /conform -ldflags "-X \"github.com/{{ .Repository }}/pkg/version.SHA={{ .Git.SHA }}\" -X \"github.com/{{ .Repository }}/pkg/version.Built={{ .Built }}\""
      {{ else }}
      RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /conform
      {{ end }}
  test:
    template: |
      {{ fromURL "https://raw.githubusercontent.com/autonomy/conform-templates/master/golang/Dockerfile.test" }}
  image:
    template: |
      FROM alpine:3.6 as image
      MAINTAINER Andrew Rynhard <andrew.rynhard@autonomy.io>
      RUN apk --update add bash \
          && rm -rf /var/cache/apk/*
      COPY --from=binary /conform /bin
      ENTRYPOINT ["conform"]
