policies:
- type: commit
  spec:
    headerLength: 89
    dco: true
    gpg: true
    imperative: true
    conventional:
      types:
      - chore
      - docs
      - perf
      - refactor
      - style
      - test
      scopes:
      - policy
- type: license
  spec:
    includeSuffixes:
    - .go
    headerFile: LICENSE_HEADER
